/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/custom-script[.]js'
import { Route as PathlessLayoutRouteImport } from './routes/_pathless-layout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathless-layout/_nested-layout'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated.posts'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated.users/index'
import { Route as AuthenticatedPostsIndexRouteImport } from './routes/_authenticated.posts/index'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathless-layout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathless-layout/_nested-layout/route-a'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated.users/$user-id'
import { Route as AuthenticatedPostsPostIdRouteImport } from './routes/_authenticated.posts/$post-id'
import { Route as AuthenticatedPostsPostIdDeepRouteImport } from './routes/_authenticated.posts_/$post-id/deep'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/custom-script.js',
  path: '/custom-script.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathless-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedPostsIndexRoute = AuthenticatedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPostsRoute,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$user-id',
    path: '/$user-id',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedPostsPostIdRoute =
  AuthenticatedPostsPostIdRouteImport.update({
    id: '/$post-id',
    path: '/$post-id',
    getParentRoute: () => AuthenticatedPostsRoute,
  } as any)
const AuthenticatedPostsPostIdDeepRoute =
  AuthenticatedPostsPostIdDeepRouteImport.update({
    id: '/posts_/$post-id/deep',
    path: '/posts/$post-id/deep',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-script.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/posts': typeof AuthenticatedPostsRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$post-id': typeof AuthenticatedPostsPostIdRoute
  '/users/$user-id': typeof AuthenticatedUsersUserIdRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/': typeof AuthenticatedPostsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/posts/$post-id/deep': typeof AuthenticatedPostsPostIdDeepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-script.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$post-id': typeof AuthenticatedPostsPostIdRoute
  '/users/$user-id': typeof AuthenticatedUsersUserIdRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts': typeof AuthenticatedPostsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/posts/$post-id/deep': typeof AuthenticatedPostsPostIdDeepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_pathless-layout': typeof PathlessLayoutRouteWithChildren
  '/custom-script.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_pathless-layout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/_authenticated/posts/$post-id': typeof AuthenticatedPostsPostIdRoute
  '/_authenticated/users/$user-id': typeof AuthenticatedUsersUserIdRoute
  '/_pathless-layout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathless-layout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/_authenticated/posts/': typeof AuthenticatedPostsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/posts_/$post-id/deep': typeof AuthenticatedPostsPostIdDeepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-script.js'
    | '/deferred'
    | '/login'
    | '/redirect'
    | '/posts'
    | '/users'
    | '/api/users'
    | '/posts/$post-id'
    | '/users/$user-id'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/users/$userId'
    | '/posts/'
    | '/users/'
    | '/posts/$post-id/deep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-script.js'
    | '/deferred'
    | '/login'
    | '/redirect'
    | '/api/users'
    | '/posts/$post-id'
    | '/users/$user-id'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/users/$userId'
    | '/posts'
    | '/users'
    | '/posts/$post-id/deep'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_pathless-layout'
    | '/custom-script.js'
    | '/deferred'
    | '/login'
    | '/redirect'
    | '/_authenticated/posts'
    | '/_authenticated/users'
    | '/_pathless-layout/_nested-layout'
    | '/api/users'
    | '/_authenticated/posts/$post-id'
    | '/_authenticated/users/$user-id'
    | '/_pathless-layout/_nested-layout/route-a'
    | '/_pathless-layout/_nested-layout/route-b'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/users/$userId'
    | '/_authenticated/posts/'
    | '/_authenticated/users/'
    | '/_authenticated/posts_/$post-id/deep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  LoginRoute: typeof LoginRoute
  RedirectRoute: typeof RedirectRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-script.js': {
      id: '/custom-script.js'
      path: '/custom-script.js'
      fullPath: '/custom-script.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-layout': {
      id: '/_pathless-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-layout/_nested-layout': {
      id: '/_pathless-layout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/posts/': {
      id: '/_authenticated/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthenticatedPostsIndexRouteImport
      parentRoute: typeof AuthenticatedPostsRoute
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-layout/_nested-layout/route-b': {
      id: '/_pathless-layout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathless-layout/_nested-layout/route-a': {
      id: '/_pathless-layout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_authenticated/users/$user-id': {
      id: '/_authenticated/users/$user-id'
      path: '/$user-id'
      fullPath: '/users/$user-id'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/posts/$post-id': {
      id: '/_authenticated/posts/$post-id'
      path: '/$post-id'
      fullPath: '/posts/$post-id'
      preLoaderRoute: typeof AuthenticatedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedPostsRoute
    }
    '/_authenticated/posts_/$post-id/deep': {
      id: '/_authenticated/posts_/$post-id/deep'
      path: '/posts/$post-id/deep'
      fullPath: '/posts/$post-id/deep'
      preLoaderRoute: typeof AuthenticatedPostsPostIdDeepRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPostsRouteChildren {
  AuthenticatedPostsPostIdRoute: typeof AuthenticatedPostsPostIdRoute
  AuthenticatedPostsIndexRoute: typeof AuthenticatedPostsIndexRoute
}

const AuthenticatedPostsRouteChildren: AuthenticatedPostsRouteChildren = {
  AuthenticatedPostsPostIdRoute: AuthenticatedPostsPostIdRoute,
  AuthenticatedPostsIndexRoute: AuthenticatedPostsIndexRoute,
}

const AuthenticatedPostsRouteWithChildren =
  AuthenticatedPostsRoute._addFileChildren(AuthenticatedPostsRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedPostsPostIdDeepRoute: typeof AuthenticatedPostsPostIdDeepRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPostsRoute: AuthenticatedPostsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedPostsPostIdDeepRoute: AuthenticatedPostsPostIdDeepRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  LoginRoute: LoginRoute,
  RedirectRoute: RedirectRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
